#ifndef __DB_INC_H
#define __DB_INC_H
#include <AP_JSUM.H>
#include <AR_JSUM.H>
#include <GL_SUM.H>
#include <GL_REPTS.H>
#include <DB_ACCES.H>
#include <DB_APDST.H>
#include <DB_APBTC.H>
#include <DB_VEND.H>
#include <DB_ACCTS.H>
#include <DB_DRCOD.H>
#include <DB_APSET.H>
#include <DB_PROFI.H>
#include <DB_REPT.H>
#include <DB_REQST.H>
#include <DB_SETUP.H>
#include <DB_JSUM.H>
#include <DB_CASH.H>
#include <DB_ACCT.H>
#include <DB_ACCT1.H>
#include <DB_ALLOC.H>
#include <DB_ARBTC.H>
#include <DB_ARDST.H>
#include <DB_ARJSM.H>
#include <DB_BTCH.H>
#include <DB_BTCHD.H>
#include <DB_CUST.H>
#include <DB_DEPT.H>
#include <DB_DIST.H>
#include <DB_DISTD.H>
#include <DB_FA.H>
#include <DB_GLSUM.H>
#include <DB_INDEX.H>
#include <DB_ITEMM.H>
#include <DB_MEDRP.H>
#include <DB_SRCE.H>
#include <DB_TAG.H>
#include <DB_XACCT.H>
#endif
