
typedef void* RESULT;
#define DLLFUNC WINAPI _export

extern "C" {
LPSTR DLLFUNC Query(LPSTR lpQuery);
LPSTR DLLFUNC CB(LPSTR szAccount,LPSTR szDept);
LPSTR DLLFUNC DESC(LPSTR szAccount,LPSTR szDept);
LPSTR DLLFUNC PD(LPSTR szAccount,LPSTR szDept,LPSTR szPeriod);

LPSTR DLLFUNC PD1(LPSTR szAccount,LPSTR szDept);
LPSTR DLLFUNC PD2(LPSTR szAccount,LPSTR szDept);
LPSTR DLLFUNC PD3(LPSTR szAccount,LPSTR szDept);
LPSTR DLLFUNC PD4(LPSTR szAccount,LPSTR szDept);
LPSTR DLLFUNC PD5(LPSTR szAccount,LPSTR szDept);
LPSTR DLLFUNC PD6(LPSTR szAccount,LPSTR szDept);
LPSTR DLLFUNC PD7(LPSTR szAccount,LPSTR szDept);
LPSTR DLLFUNC PD8(LPSTR szAccount,LPSTR szDept);
LPSTR DLLFUNC PD9(LPSTR szAccount,LPSTR szDept);
LPSTR DLLFUNC PD10(LPSTR szAccount,LPSTR szDept);
LPSTR DLLFUNC PD11(LPSTR szAccount,LPSTR szDept);
LPSTR DLLFUNC PD12(LPSTR szAccount,LPSTR szDept);

}

