#define ID_ACCT
#define ID_BOTTOM
#define ID_BUDGET
#define ID_COL
#define ID_COPY
#define ID_DASH4008
#define ID_DASHDOT4010
#define ID_DOT4009
#define ID_FORMULA4015
#define ID_ITEM3895
#define ID_LEFT4005
#define ID_NONE4006
#define ID_NUMBER3892
#define ID_OUTLINE4001
#define ID_PERIOD4012
#define ID_RIGHT4004
#define ID_ROW3889
#define ID_SOL#define ID4007
#define ID_TEXT3891
#define ID_TOP4002
#define ID_TOTAL4011
#define ID_UPDATEAP7001
#define IDS_MENUITEM4017
#define IDS_READY4016
#define IDS_SYSTEM4018
#define CM_CURRENTBATCH
#define CM_DIALOGPRINT2001
#define CM_DIALOGPRINT2001
#define CM_SUMMARY
#define GL_YEAREND1072
#define GL_YEAREND1073
#define ID_ACCOUNTS
#define ID_ACCOUNTS
#define ID_ACCTADD
#define ID_ACCTADD
#define ID_ACCTBUDGET10074
#define ID_ACCTBUDGET10074
#define ID_ACCTDEL
#define ID_ACCTDEL
#define ID_ACCTLIST
#define ID_ACCTLIST
#define ID_ACCTMOD
#define ID_ACCTMOD
#define ID_ADD
#define ID_ADJBATCH
#define ID_ADJBATCH
#define ID_ADJCANCEL
#define ID_ADJCANCEL
#define ID_ADJPOSTING
#define ID_ADJPOSTING
#define ID_ADJUSTMENT
#define ID_AGEDCASH
#define ID_AGEDCASH
#define ID_AGEDRETAIN
#define ID_AGEDRETAIN
#define ID_AP
#define ID_AP
#define ID_APADDVENDORS
#define ID_APADJUSTMENT
#define ID_APCASH
#define ID_APDELVENDORS
#define ID_APDELVENDORS
#define ID_APDEPART
#define ID_APINQVENDORS
#define ID_APINQVENDORS
#define ID_APMODVENDORS
#define ID_APMODVENDORS
#define ID_APPOSTADJ
#define ID_APPOSTBATCH
#define ID_APPOSTBATCH
#define ID_APPOSTJOURNAL
#define ID_APPOSTJOURNAL
#define ID_APPRINTADJ
#define ID_APPRINTBATCH
#define ID_APPRINTBATCH
#define ID_APPRINTCASH
#define ID_AR
#define ID_AR
#define ID_AR_PRTREPS
#define ID_AR_PRTREPS
#define ID_AR306090
#define ID_AR306090
#define ID_ARBILLINGS
#define ID_ARBILLINGS
#define ID_ARCHARGES
#define ID_ARCHARGES
#define ID_ARCNTRACCTS
#define ID_ARCNTRACCTS
#define ID_ARGENERAL
#define ID_ARGENERAL
#define ID_ARMAINSPECS
#define ID_ARMAINSPECS
#define ID_ARPAYMENTS
#define ID_ARPAYMENTS
#define ID_BACKUP
#define ID_BATCHENT
#define ID_BATCHENT
#define ID_BATCHLIST
#define ID_BATCHLIST
#define ID_BATCHSTATUS
#define ID_BATCHSTATUS
#define ID_BATCHSUM10131
#define ID_BATCHSUM10131
#define ID_BM
#define ID_BS
#define ID_BS
#define ID_CANCELBATCH
#define ID_CANCELBATCH
#define ID_CASH
#define ID_CASH
#define ID_CASHCANCEL
#define ID_CHART
#define ID_CHART
#define ID_CLOSEM1069
#define ID_CLOSEM1069
#define ID_COMPANY
#define ID_CONSOL#define IDATE
#define ID_CONSOL#define IDATE
#define ID_COSTALLOC
#define ID_CURRBAL
#define ID_CURRBAL
#define ID_DELCUST10251
#define ID_DELCUST10251
#define ID_DEPART
#define ID_DEPART
#define ID_DEPTCODE
#define ID_DEPTCODE
#define ID_DEPTCODES10061
#define ID_DEPTCODES10061
#define ID_DESCRIPT
#define ID_DISTLIST
#define ID_DISTLIST
#define ID_DISTSMRY1070
#define ID_DISTSMRY1070
#define ID_EACCOUNTS
#define ID_EACCOUNTS
#define ID_EDEPART
#define ID_EDEPART
#define ID_EXTBATCH
#define ID_EXTBATCH
#define ID_FA1103
#define ID_FINBS
#define ID_FINBS
#define ID_FINDEP
#define ID_FINDEP
#define ID_FINFA
#define ID_FINFA
#define ID_FININCOME
#define ID_FININCOME
#define ID_FINRE
#define ID_FINRE
#define ID_FINSCFP
#define ID_FINSCFP
#define ID_GL
#define ID_GL
#define ID_GLBUDGETINQ10073
#define ID_GLBUDGETINQ10073
#define ID_GLCHARTINQ10071
#define ID_GLCHARTINQ10071
#define ID_GLSLIP
#define ID_GLTRANS
#define ID_GLTRANS
#define ID_GLTRANSINQ10072
#define ID_GLTRANSINQ10072
#define ID_INQCUST
#define ID_INQCUST
#define ID_INQREPORTS
#define ID_INQREPORTS
#define ID_INQTRANS
#define ID_INQTRANS
#define ID_INVOICE
#define ID_INVOICE
#define ID_IS
#define ID_IS
#define ID_MAINCUST
#define ID_MAINCUST
#define ID_MAINDEPT
#define ID_MAINDEPT
#define ID_MAINGROUP
#define ID_MAINGROUP
#define ID_MAINSOURCE
#define ID_MAINSOURCE
#define ID_MAINSPEC
#define ID_MAINSPEC
#define ID_MODBATCH10076
#define ID_MODBATCH10076
#define ID_MODCUST1026
#define ID_MODCUST1026
#define ID_MODIFY
#define ID_MODIFY
#define ID_NEXT
#define ID_OPEN
#define ID_OPEN
#define ID_OPENACCTS
#define ID_OPENACCTS
#define ID_OPENBAL
#define ID_OPENBAL
#define ID_OPENOVD
#define ID_OPENOVD
#define ID_OVERDUE
#define ID_OVERDUE
#define ID_PREPAYMENT
#define ID_PREVIOUS
#define ID_PURGEACCTS
#define ID_PURGEACCTS
#define ID_RE
#define ID_RE
#define ID_RESTORE
#define ID_SCS1104
#define ID_SETDATA
#define ID_SLIPLIST1074
#define ID_SOURCEJ
#define ID_SOURCEJ
#define ID_TBALANCE
#define ID_TBALANCE
#define ID_TOOLBAR10041
#define ID_TOOLBAR10041
#define ID_TOPICS
#define ID_TOPICS
#define ID_TYPE
#define ID_TYPE
#define ID_VENDORACCT
#define ID_VENDORACCT
#define ID_VENDORRECEIPT
#define ID_VENDORRECON
#define ID_VENLISTS
#define ID_VENLISTS
#define ID_VENPAYMENT
#define ID_VENPAYMENT
#define ID_VENSCHEDULE
#define ID_VENSCHEDULE
#define ID_YEAREND
#define ID_YEAREND
#define IDINQOPTIONS3002
#define IDINQOPTIONS3002
#define IDLISTBOX2001
#define IDLISTBOX2001
#define IDMAINOPTIONS3001
#define IDMAINOPTIONS3001
#define IDPRINTBOX2012
#define IDPRINTBOX2012
#define IDPRINTCHECK2011
#define IDPRINTCHECK2011
#define IDREPORTNAME2010
#define IDREPORTNAME2010
#define AP_ADJCANCEL
#define CM_AP_BTCHD
#define CM_AP_CASHD
#define CM_AP_JSUM
#define CM_BATCH4102
#define CM_CASH_JSUM
#define CM_CHEQUE_AP
#define CM_CHEQUE_CASH
#define CM_CHEQUE_REPORT
#define CM_FILESETUP
#define CM_GLDETAIL
#define CM_GLSUMMARY
#define CM_LINEITEM
#define CM_NEW
#define CM_REBATE_REPORT8071
#define CM_SETDATA
#define CM_SETVENDOR
#define CM_VATAP_REPORT
#define CM_VATGL_REPORT
#define ID_ABOUT6072
#define ID_ABOUT6072
#define ID_ACCEPT
#define ID_ACCOUNT
#define ID_ACCOUNTSEARCH
#define ID_ACCOUNTSEARCH
#define ID_ACCOUNTSEARCH3042
#define ID_ACCOUNTSEARCH3042
#define ID_ACCTSINQUIRY
#define ID_ACCTSINQUIRY
#define ID_ACCTSPAYABLELIST
#define ID_ADD
#define ID_ADDRESS1
#define ID_ADDRESS1
#define ID_ADDRESS2
#define ID_ADDRESS2
#define ID_ADDRESS3
#define ID_ADDRESS3
#define ID_ADJBATCHPRINT
#define ID_ADJPRINT
#define ID_ADJUST
#define ID_ADJUSTMENT
#define ID_AMOUNT
#define ID_AMOUNTDUE4013
#define ID_APADD
#define ID_APADD4043
#define ID_APADDVENDORS
#define ID_APBATCH4044
#define ID_APBATCH4044
#define ID_APBATCHENT4013
#define ID_APBATCHENT4013
#define ID_APCONTROL1087
#define ID_APINQ4046
#define ID_APINQ4046
#define ID_APMODIFY
#define ID_APPOST4045
#define ID_APPOST4045
#define ID_APPOSTCASH
#define ID_ARADD4047
#define ID_ARBALANCE
#define ID_ARBALANCE
#define ID_ARBATCH4048
#define ID_ARBATCHENT4014
#define ID_ARBATCHENT4014
#define ID_ARCREDITBAL
#define ID_ARCREDITBAL
#define ID_ARINQ4050
#define ID_ARPOST4049
#define ID_ATBATCH
#define ID_AUTO
#define ID_BACK
#define ID_BACK
#define ID_BANK
#define ID_BATCHADJUSTED4096
#define ID_BATCHCANCEL3064
#define ID_BATCHCANCEL3064
#define ID_BATCHDELETE
#define ID_BATCHDELETE
#define ID_BATCHNO
#define ID_BATCHNO
#define ID_BATCHSEARCH
#define ID_BATCHSEARCH
#define ID_BATCHSEARCH3041
#define ID_BATCHSEARCH3041
#define ID_BLANKFIELD
#define ID_BLANKFIELD
#define ID_BOTTOM
#define ID_BTCHLISTD
#define ID_BTCHLISTD
#define ID_BUDGETAMOUNT
#define ID_BUDGETLIST
#define ID_BUDGETUPDATE
#define ID_CALCULATOR
#define ID_CANCEL
#define ID_CANCELINVOICE3046
#define ID_CANCELINVOICE3046
#define ID_CHANGE4047
#define ID_CHEQUE6070
#define ID_CHEQUE6070
#define ID_CLOSEDINVOICE_BATCH998
#define ID_CODE
#define ID_CODE
#define ID_COMPANY
#define ID_COMPANYPROFILE6015
#define ID_COMPANYPROFILE6015
#define ID_CONTACT
#define ID_CONTACT
#define ID_CONTROL
#define ID_CREATEADJ
#define ID_CREDIT
#define ID_CREDIT
#define ID_CREDITTOTAL
#define ID_CREDITTOTAL
#define ID_CURRENTBATCH
#define ID_CUSTOMERNO
#define ID_CUSTOMERNO
#define ID_CUSTOMREPORT4025
#define ID_CUSTOMREPORT4025
#define ID_DATE
#define ID_DATE
#define ID_DEBIT
#define ID_DEBIT
#define ID_DEBITTOTAL
#define ID_DEBITTOTAL
#define ID_DELETE1118
#define ID_DELETE1118
#define ID_DESCRIPT
#define ID_DIFFERENCE
#define ID_DIFFERENCE
#define ID_DUEDATE
#define ID_DUEDATE
#define ID_ENTERINVDATE
#define ID_ENTERINVOICE
#define ID_ENTRYNO
#define ID_ENTRYNO
#define ID_ERROR
#define ID_ERROR
#define ID_FAX
#define ID_FAX
#define ID_FILENAME
#define ID_FIVE
#define ID_FORCE
#define ID_FORWARD
#define ID_FORWARD
#define ID_GENERAL6082
#define ID_GENERAL6082
#define ID_GLADD4051
#define ID_GLBATCH4052
#define ID_GLINQ4054
#define ID_GLPOST4053
#define ID_GLPOSTBATCH
#define ID_GLPOSTBATCH
#define ID_GLREPBATCH10122
#define ID_GLREPBATCH10122
#define ID_HELP6073
#define ID_HELP6073
#define ID_H#define IDEDIST
#define ID_HOLD
#define ID_INDIV#define IDUAL
#define ID_INPUTERROR
#define ID_INPUTERROR
#define ID_INST_REPORT
#define ID_INST_REPORT
#define ID_INST_TITLE
#define ID_INST_TITLE
#define ID_INVDATE
#define ID_INVDATE
#define ID_INVOICEADJ
#define ID_INVOICEBATCH
#define ID_INVOICEBATCH
#define ID_INVOICECREATED4086
#define ID_INVOICENO4012
#define ID_JDESCRIPT
#define ID_JDESCRIPT
#define ID_LINENO
#define ID_LINENO
#define ID_MANUFACT6083
#define ID_MANUFACT6083
#define ID_MODIFYBATCH3062
#define ID_MODIFYBATCH3062
#define ID_MODIFYINVOICE3044
#define ID_MODIFYINVOICE3044
#define ID_NEW
#define ID_NEWBATCH
#define ID_NEWBATCH3061
#define ID_NEWBATCH3061
#define ID_NEWINVOICE3045
#define ID_NEWINVOICE3045
#define ID_NEXT1071
#define ID_NEXTONE
#define ID_NEXTONE
#define ID_NOBATCH4085
#define ID_NOINVOICES
#define ID_ORDERNO
#define ID_ORDERNO
#define ID_PAYMENT6085
#define ID_PD1_DESC
#define ID_PD1_DESC
#define ID_PD10_DESC
#define ID_PD10_DESC
#define ID_PD11_DESC
#define ID_PD11_DESC
#define ID_PD12_DESC
#define ID_PD12_DESC
#define ID_PD2_DESC
#define ID_PD2_DESC
#define ID_PD3_DESC
#define ID_PD3_DESC
#define ID_PD4_DESC
#define ID_PD4_DESC
#define ID_PD5_DESC
#define ID_PD5_DESC
#define ID_PD6_DESC
#define ID_PD6_DESC
#define ID_PD7_DESC
#define ID_PD7_DESC
#define ID_PD8_DESC
#define ID_PD8_DESC
#define ID_PD9_DESC
#define ID_PD9_DESC
#define ID_PERIOD
#define ID_PERIOD1
#define ID_PERIOD1
#define ID_PERIOD10
#define ID_PERIOD10
#define ID_PERIOD10E
#define ID_PERIOD10E
#define ID_PERIOD11
#define ID_PERIOD11
#define ID_PERIOD11E
#define ID_PERIOD11E
#define ID_PERIOD12
#define ID_PERIOD12
#define ID_PERIOD12E
#define ID_PERIOD12E
#define ID_PERIOD1E
#define ID_PERIOD1E
#define ID_PERIOD2
#define ID_PERIOD2
#define ID_PERIOD2E
#define ID_PERIOD2E
#define ID_PERIOD3
#define ID_PERIOD3
#define ID_PERIOD3E
#define ID_PERIOD3E
#define ID_PERIOD4
#define ID_PERIOD4
#define ID_PERIOD4E
#define ID_PERIOD4E
#define ID_PERIOD5
#define ID_PERIOD5
#define ID_PERIOD5E
#define ID_PERIOD5E
#define ID_PERIOD6
#define ID_PERIOD6
#define ID_PERIOD6E
#define ID_PERIOD6E
#define ID_PERIOD7
#define ID_PERIOD7
#define ID_PERIOD7E
#define ID_PERIOD7E
#define ID_PERIOD8
#define ID_PERIOD8
#define ID_PERIOD8E
#define ID_PERIOD8E
#define ID_PERIOD9
#define ID_PERIOD9
#define ID_PERIOD9E
#define ID_PERIOD9E
#define ID_PERIODE3066
#define ID_PERIODE3066
#define ID_PERIODS
#define ID_PERIODS
#define ID_PHONE6069
#define ID_PHONE6069
#define ID_POST
#define ID_POST
#define ID_POSTING
#define ID_POSTING
#define ID_PREPOST6078
#define ID_PREPOST6078
#define ID_PREVIOSONE
#define ID_PREVIOSONE
#define ID_PREVIOUS
#define ID_PRINT3068
#define ID_PRINT3068
#define ID_PRINTERROR16009
#define ID_PRINTERROR16009
#define ID_PRTADJPOSTING
#define ID_PRTDEPT6079
#define ID_PRTDEPT6079
#define ID_QUICKENTRY
#define ID_QUICKMODIFY4064
#define ID_REBATE
#define ID_REBATEADJ
#define ID_RECALC6016
#define ID_RECALC6016
#define ID_RECOVER
#define ID_REFERENCE
#define ID_REFERENCE
#define ID_REINDEX
#define ID_REQUEST
#define ID_REQUESTDETAIL
#define ID_REQUESTNO
#define ID_REQUESTSUM
#define ID_RETAINED
#define ID_RETAINED
#define ID_SAVE4055
#define ID_SEARCH
#define ID_SEARCH4062
#define ID_SEARCHCUST3043
#define ID_SEARCHCUST3043
#define ID_SEARCHGL3063
#define ID_SEARCHGL3063
#define ID_SELLING6081
#define ID_SELLING6081
#define ID_SET4019
#define ID_SETDATA
#define ID_SETDATE
#define ID_SETDETAIL
#define ID_SETPERIOD
#define ID_SETPERIOD
#define ID_SLIP6074
#define ID_SLIP6074
#define ID_SLIP_DESCRIPTION4084
#define ID_SLIPDETAILS
#define ID_SLIPSUM6075
#define ID_SLIPSUM6075
#define ID_SOURCECODE
#define ID_SOURCECODE
#define ID_SPREAD
#define ID_SYSINDEX
#define ID_TB6076
#define ID_TB6076
#define ID_TBBYDEPT6080
#define ID_TBBYDEPT6080
#define ID_TEL
#define ID_TEL
#define ID_TERMS
#define ID_THREE3181
#define ID_TOP
#define ID_TOTAL
#define ID_TRANSINQUIRY
#define ID_TRANSINQUIRY
#define ID_TRASH
#define ID_TRYAGAIN
#define ID_UPDATEGL
#define ID_VAT
#define ID_VATPERCENTAGE4065
#define ID_VENDORADDRESS1
#define ID_VENDORADDRESS1
#define ID_VENDORADDRESS2
#define ID_VENDORADDRESS2
#define ID_VENDORADDRESS3
#define ID_VENDORADDRESS3
#define ID_VENDORCODE
#define ID_VENDORCONTACT
#define ID_VENDORCONTACT
#define ID_VENDORNAME
#define ID_VENDORNAME
#define ID_VENDORNO
#define ID_VENDORNO
#define ID_VENDORPOST
#define ID_VENDORPOST
#define ID_VENDORREF
#define ID_VENDORREF
#define ID_VENDORSHORT
#define ID_VENDORSHORT
#define ID_VENDORSTATUS
#define ID_VENDORSTATUS
#define ID_VENDORTEL
#define ID_VENDORTEL
#define ID_VIEWALL
#define ID_VIEWDIST
#define ID_VIEWDIST
#define ID_WARNING
#define IDC_1
#define IDC_2
#define IDC_3
#define IDC_6
#define IDC_PUSHBUTTON3
#define IDD_STATUSBOX
#define IDD_STATUSBOX
#define IDM_PRINT4015
#define IDM_PRINT4015
#define USER_CHAR_SET128
#define USER_CHAR_SIZE-15




















